### ISSUE TITLE
command-line option `--no-colors-in-output` seems to be ignored.

### ISSUE THREAD

**Issue by OriginLabs-Iguernlala** [OCamlPro/alt-ergo#318] opened 2020-07-11 08:42 UTC
With eg,
```
$ ./alt-ergo file.ae  --dsat --no-colors-in-output &> log
```
I still get colored, which is not really readable when redirecting to a file:

```
$ less log

[34m[1m[Debug][Satml_frontend][assume][22m[0m
I assume a [6-atom] lemma: (lem match_bool_True)
[34m[1m[Debug][Satml_frontend][assume][22m[0m
I assume a [6-atom] lemma: (lem match_bool_False)
[34m[1m[Debug][Satml_frontend][assume][22m[0m
I assume a [16-atom] lemma: (lem CompatOrderMult)
[34m[1m[Debug][Satml_frontend][assume][22m[0m
I assume a [5-atom] lemma: (lem length_nonnegative)
[34m[1m[Debug][Satml_frontend][assume][22m[0m
I assume a [10-atom] lemma: (lem infix_eqeqqtspec)
[34m[1m[Debug][Satml_frontend][assume][22m[0m
I assume a [24-atom] lemma: (lem infix_eqeqqtspec1)
[34m[1m[Debug][Satml_frontend][assume][22m[0m
I assume a [30-atom] lemma: (lem infix_eqeqqtspec2)
[34m[1m[Debug][Satml_frontend][assume][22m[0m
I assume a [8-atom] lemma: (lem infix_eqeqqtspec3)
[34m[1m[Debug][Satml_frontend][assume][22m[0m
```

Also, I don't understand why the solver still runs when I fire commands like (although the last option is likely not known):
```
$ ./alt-ergo file.ae  --dsat --no-colors

$ ./alt-ergo file.ae  --dsat --no-colors-in

$ ./alt-ergo file.ae  --dsat --no-colors-in-o

$ ...
```

**Comment by OCamlPro-mattiasdrp** [comment] 2020-07-11 09:06
> Also, I don't understand why the solver still runs when I fire commands like (although the last option is likely not known):
>
> ```
> $ ./alt-ergo file.ae  --dsat --no-colors
> 
> $ ./alt-ergo file.ae  --dsat --no-colors-in
> 
> $ ./alt-ergo file.ae  --dsat --no-colors-in-o
> 
> $ ...
> ```

That's actually a normal behaviour. When there's no ambiguity remaining for the terminal, it will autocomplete the rest of the option. You can try with `ls --re` that won't work but `ls --rev` will.

As for the colors in output, it is a bug indeed that will be fixed ;-)

**Comment by OriginLabs-Iguernlala** [comment] 2020-07-11 09:18
Ok, so the second option is a feature of `cmdliner` I guess :+1:

**Comment by OCamlPro-mattiasdrp** [comment] 2020-07-11 09:27
Not sure if it comes from `cmdliner` or the fact that we now have a man page since `ls` is typically a bash command but yes, for once it's not a bug, it's really a feature!

**Comment by Gbury** [comment] 2020-07-11 09:28
> Not sure if it comes from `cmdliner` or the fact that we now have a man page since `ls` is typically a bash command but yes, for once it's not a bug, it's really a feature!

It's a feature of cmdliner, ^^

**Comment by OCamlPro-Coquera** [comment] 2020-07-12 08:09
#326 should fix it

**Closed** 2020-07-12 18:10 UTC
