### ISSUE TITLE
Alt-ergo incompatible with menhir.20211125 when using ocaml 4.08, 4.09 or 4.10 ?

### ISSUE THREAD

**Issue by fblanqui** [OCamlPro/alt-ergo#492] opened 2021-11-26 09:34 UTC
Hi. I have a strange error this morning. See https://github.com/Deducteam/lambdapi/runs/4332121191?check_suite_focus=true. Alt-ergo fails when menhir is upgraded from 20211012 to 20211125 but opam info menhir mentions no 20211125 version for menhir on my machine...

**Comment by Stevendeo** [comment] 2021-11-26 12:33
It is very strange that it works with OCaml 4.11 but not in OCaml 4.10.2 (at least according to your CI). I am checking that it is also the case locally, but it might be (somehow) a bug on menhir's side.

**Comment by fblanqui** [comment] 2021-11-26 12:48
Concerning menhir 20211125, I now see it on my machine with opam info.

**Comment by Stevendeo** [comment] 2021-11-26 12:52
You're right I just noticed it too. For now I suggest you use the previous version of menhir.
My understanding is that the OCaml typer has been fixed in 4.11.0 to accept some tricky quantified types, and menhir now generates such types.

**Comment by fblanqui** [comment] 2021-11-26 12:59
I added an issue on menhir: https://gitlab.inria.fr/fpottier/menhir/-/issues/57.

**Comment by Stevendeo** [comment] 2022-06-03 11:50
If the issue is solved, I will close it

**Comment by Halbaroth** [comment] 2023-05-19 12:18
I assume the issue is fixed.

**Closed as completed by Halbaroth** 2023-05-19 12:18 UTC
