### ISSUE TITLE
MacOS cannot install alt-ergo

### ISSUE THREAD

**Issue by wzyb-52** [OCamlPro/alt-ergo#1125] opened 2024-05-15 08:57 UTC
I'm trying to install alt-ergo and meet the following problem:

```
#=== ERROR while compiling alt-ergo.2.5.3 =====================================#
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
⬇ retrieved alt-ergo.2.5.3  (cached)
[ERROR] The compilation of alt-ergo.2.5.3 failed at "dune build -p alt-ergo -j 11 --promote-install-files=false @install".

# context     2.1.3 | macos/x86_64 | ocaml-base-compiler.4.14.1 | https://opam.ocaml.org#c1bf247e
# path        ~/.opam/4.14.1/.opam-switch/build/alt-ergo.2.5.3
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p alt-ergo -j 11 --promote-install-files=false @install
# exit-code   1
# env-file    ~/.opam/log/alt-ergo-4646-833ca9.env
# output-file ~/.opam/log/alt-ergo-4646-833ca9.out
### output ###
# File "src/bin/text/dune", line 14, characters 0-94:
# 14 | (rule
# 15 |   (target alt-ergo.1)
# 16 |   (action (with-stdout-to %{target} (run alt-ergo --help=groff))))
# (cd _build/default/src/bin/text && ../../../../install/default/bin/alt-ergo --help=groff) > _build/default/src/bin/text/alt-ergo.1
# Command got signal ILL.
``` 

And the related packages are:
```
alt-ergo-lib          2.5.3       The Alt-Ergo SMT prover library
alt-ergo-parsers      2.5.3       The Alt-Ergo SMT prover parser library
dune                  3.14.0      Fast, portable, and opinionated build system
ocaml                 4.14.1      The OCaml compiler (virtual package)
menhir                20231231    An LR(1) parser generator
dune-site             3.15.2      Embed locations information inside executable and libraries
cmdliner              1.2.0       Declarative definition of command line interfaces for OCaml
```

**Comment by Halbaroth** [comment] 2024-05-15 13:28
It seems that `dune` failed to run the rule that generates the manpage from the command line. 
Did you look the output file `~/.opam/log/alt-ergo-4646-833ca9.out`?

Maybe there is a relation with the issue #1035? 
Could you try to compile `Alt-Ergo 2.5.3` from the source?
```sh 
cd /tmp
wget https://github.com/OCamlPro/alt-ergo/archive/refs/tags/v2.5.3.zip
unzip v2.5.3.zip 
cd alt-ergo-2.5.3
make dev-switch 
eval $(opam env)
make bin 
./alt-ergo --help
```
or with `Nix`
```sh 
cd /tmp
wget https://github.com/OCamlPro/alt-ergo/archive/refs/tags/v2.5.3.zip
unzip v2.5.3.zip 
cd alt-ergo-2.5.3
nix-shell
make bin 
./alt-ergo --help
```

**Comment by Halbaroth** [comment] 2024-07-11 14:24
@wzyb-52 did you manage to install alt-ergo?

**Comment by wzyb-52** [comment] 2024-07-12 00:20
I successfully installed it on another Mac, and do not know why.



---Original---
From: ***@***.***&gt;
Date: Thu, Jul 11, 2024 22:25 PM
To: ***@***.***&gt;;
Cc: "Zhongyi ***@***.******@***.***&gt;;
Subject: Re: [OCamlPro/alt-ergo] MacOS cannot install alt-ergo (Issue #1125)




 
@wzyb-52 did you manage to install alt-ergo?

**Comment by Halbaroth** [comment] 2024-07-16 09:40
Ok, glad to hear that it works now. I close the issue as we cannot reproduce it.

**Closed as completed by Halbaroth** 2024-07-16 09:40 UTC
Labels: build
